-- Your SQL goes here

-- CREATE TABLE tags (
--     id INTEGER PRIMARY KEY,
--     name TEXT NOT NULL COLLATE NOCASE,
--     UNIQUE (name)
-- )

CREATE TABLE tags
(
    id SERIAL PRIMARY KEY,
    order_index INTEGER NOT NULL DEFAULT 0,
    name TEXT NOT NULL,
    parent INTEGER NOT NULL DEFAULT 0,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (name)
)