
[workspace]
members = [
  "backend",
  "calibre",
  "cip",
  "frontend",
  "shared",
]

resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = "abort"
strip = "symbols"
