-- Your SQL goes here

CREATE TABLE cips_authors_link
(
    id SERIAL PRIMARY KEY NOT NULL,
    cip INTEGER NOT NULL,
    author INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(cip, author)
)