-- Your SQL goes here

CREATE TABLE douban_authors
(
    id SERIAL PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    url TEXT NOT NULL DEFAULT '',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (name)
)