
FROM rust:1.70-bookworm as pf-build-1
RUN cargo install --locked trunk
RUN cargo install --locked wasm-bindgen-cli
RUN rustup target add wasm32-unknown-unknown

FROM pf-build-1 as pf-build-2
COPY . /build
WORKDIR /build
RUN cd frontend && trunk build --release

FROM nginx:1.23
COPY --from=pf-build-2 /build/frontend/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
