FROM rust:bullseye as builder
COPY . /build
WORKDIR /build

RUN cargo install --locked trunk
RUN cargo install --locked wasm-bindgen-cli
RUN cd frontend && ../trunk build --release
#RUN wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
#RUN cd frontend && ../trunk build --release

FROM nginx:1.23

COPY --from=0 /build/frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
