version: "3.0"
services:
  pengzu_backend_db:
    image: postgres:15.3
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: pengzu-password
      POSTGRES_USER: postgres
      POSTGRES_DB: pengzu
    volumes:
      - /docker/pengzu:/var/lib/postgresql
      - /docker/pengzu/data:/var/lib/postgresql/data
