[package]
name = "cip"
version = "0.1.0"
homepage = "https://github.com/xushaohua/pengzu"
repository = "https://github.com/xushaohua/pengzu"
edition = "2021"
publish = false

[dependencies]
clap = "4.3.2"
encoding = "0.2.33"
epub = "2.0.0"
html2text = "0.6.0"
lopdf = "0.31.0"
mobi = "0.8.0"
